CREATE TABLE ZOMATO.USER5(
ID INT PRIMARY KEY,
NAME VARCHAR(45) NOT NULL,
MOBILENO INT CHECK(LENGTH (MOBILENO)=10),
AGE INT CHECK (AGE>=18)
);
SELECT * FROM ZOMATO.USER5;
INSERT INTO ZOMATO.USER5(ID,NAME,MOBILENO,AGE) VALUES(1,"AAMANI",9959440321,20);

CREATE TABLE ZOMATO.USER6(
ID INT PRIMARY KEY,
NAME VARCHAR(45) NOT NULL,
STATE VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) DEFAULT('INDIA')
);
SELECT * FROM ZOMATO.USER6;
INSERT INTO ZOMATO.USER6(ID,NAME,STATE) VALUES(1,'AAMANI','AP');

CREATE TABLE ZOMATO.USER7(
ID INT PRIMARY KEY auto_increment,
NAME VARCHAR(45) NOT NULL,
MOBILENO INT CHECK(LENGTH(MOBILENO)=10),
AGE INT CHECK(AGE>=18)
);
SELECT * FROM ZOMATO.USER7;
INSERT INTO ZOMATO.USER7(ID,NAME,MOBILENO,AGE) VALUES(1,'AAMANI',1234567890,20);