SELECT * FROM ZOMATO.USER;
INSERT INTO ZOMATO.USER(ID,NAME,EMAIL,STATE,COUNTRY,PINCODE)
VALUES(1,'AAMANI','A@GMAIL.COM','AP','INDIA',523292),
(2,'TEJA','T@GMAIL.COM','TS','INDIA',523292),
(3,'VIDYA','V@GMAIL.COM','AP','INDIA',500000);
UPDATE ZOMATO.USER SET NAME='AKKI'WHERE ID=2;
DELETE FROM ZOMATO.USER WHERE NAME='AAMANI';